# yaml-language-server: $schema=../../schemas/hugo.json
baseURL: http://localhost/
defaultContentLanguage: en
enableGitInfo: true
languages:
  en:
    languageName: English
    weight: 1
  pt:
    languageName: PortuguÃªs
    weight: 2
    contentDir: content/pt
copyright: |
  Â© 2013 - 2026 Thiago Perrotta Â·
    [some rights reserved](https://creativecommons.org/licenses/by-nc-sa/4.0/) Â·
    a fork of [hugo Ê•â€¢á´¥â€¢Ê” bear](https://github.com/janraasch/hugo-bearblog/)
languageCode: en-us
enableRobotsTxt: true
buildDrafts: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 4
rssLimit: 40
title: Â¬ just serendipity ğŸ€
menu:
  main:
    - name: â˜…
      url: /tags/bestof/
      weight: 1
      params:
        emoji: â­
    - name: ğŸ”
      url: /search/
      weight: 2
    - name: Blog
      url: /posts/
      weight: 3
    - name: Explore
      url: "#"
      weight: 4
      params:
        dropdown: true
    - name: Projects
      url: /projects/
      weight: 40
      parent: Explore
    - name: Blogroll
      url: /blogroll/
      weight: 41
      parent: Explore
    - name: ğŸ·ï¸ Tags
      url: /tags/
      weight: 42
      parent: Explore
    - name: Serenity
      url: /tags/serenity/
      weight: 43
      parent: Explore
    - name: ğŸ“‚ Categories
      url: /categories/
      weight: 44
      parent: Explore
    - name: ğŸ’» Coding
      url: /categories/coding/
      weight: 45
      parent: Explore
    - name: ğŸ•¸ï¸ Graph
      url: /graph/
      weight: 46
      parent: Explore
    - name: ğŸ² Random
      url: /random/
      weight: 47
      parent: Explore
    - name: ğŸ“» Radio
      url: /radio/
      weight: 48
      parent: Explore
    - name: ğŸ… Pomodoro
      url: /pomodoro/
      weight: 49
      parent: Explore
params:
  author:
    email: serendipity@perrotta.dev
    name: Thiago Perrotta
    nickname: thiagowfx
  description: not just serendipity, the blog from Thiago Perrotta
  appleTouchIcon: apple-touch-icon.webp
  favicon: favicon.ico
  oldEntryWarningYears: 1
  jwzPreviouslyLimit: 5
  featuredPostsLimit: 3
permalinks:
  posts: "/:year/:month/:slug/"
taxonomies:
  tag: tags
  category: categories

# llms.txt BEGIN
# layouts/_default/home.llms.txt
mediaTypes:
  text/markdown:
    suffixes:
      - md
  application/opml:
    suffixes:
      - opml
outputFormats:
  Markdown:
    mediaType: text/markdown
    baseName: index
    isPlainText: true
  llms:
    mediaType: text/plain
    baseName: llms
    isPlainText: true
  OPML:
    mediaType: application/opml
    baseName: blogroll
    isPlainText: false
  search:
    mediaType: application/json
    baseName: index
    isPlainText: true
  graphdata:
    mediaType: application/json
    baseName: graph
    isPlainText: true
outputs:
  home:
    - HTML
    - RSS
    - llms
    - OPML
  page:
    - HTML
    - Markdown
# llms.txt END
