# yaml-language-server: $schema=../../schemas/hugo.json
baseURL: http://localhost/
defaultContentLanguage: en
enableGitInfo: true
languages:
  en:
    languageName: English
    weight: 1
  pt:
    languageName: Portugu√™s
    weight: 2
    contentDir: content/pt
copyright: |
  ¬© 2021 - 2026 Thiago Perrotta ¬∑
    [some rights reserved](https://creativecommons.org/licenses/by-nc-sa/4.0/) ¬∑
    a fork of [hugo  ï‚Ä¢·¥•‚Ä¢ î bear](https://github.com/janraasch/hugo-bearblog/)
languageCode: en-us
enableRobotsTxt: true
buildDrafts: true
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 4
rssLimit: 40
title: ¬¨ just serendipity üçÄ
menu:
  main:
    - name: ‚òÖ
      url: /tags/bestof/
      weight: 1
      params:
        emoji: ‚≠ê
    - name: üîç
      url: /search/
      weight: 2
    - name: Blog
      url: /posts/
      weight: 3
    - name: Explore
      url: "#"
      weight: 4
      params:
        dropdown: true
    - name: Projects
      url: /projects/
      weight: 40
      parent: Explore
    - name: Blogroll
      url: /blogroll/
      weight: 41
      parent: Explore
    - name: Tags
      url: /tags/
      weight: 42
      parent: Explore
    - name: Categories
      url: /categories/
      weight: 43
      parent: Explore
    - name: Coding
      url: /categories/coding/
      weight: 44
      parent: Explore
params:
  author:
    email: serendipity@perrotta.dev
    name: Thiago Perrotta
    nickname: thiagowfx
  description: not just serendipity, the blog from Thiago Perrotta
  appleTouchIcon: apple-touch-icon.webp
  favicon: favicon.ico
  oldEntryWarningYears: 1
  jwzPreviouslyLimit: 7
permalinks:
  posts: "/:year/:month/:slug/"
taxonomies:
  tag: tags
  category: categories

# llms.txt BEGIN
# layouts/_default/home.llms.txt
mediaTypes:
  text/markdown:
    suffixes:
      - md
  application/opml:
    suffixes:
      - opml
outputFormats:
  Markdown:
    mediaType: text/markdown
    baseName: index
    isPlainText: true
  llms:
    mediaType: text/plain
    baseName: llms
    isPlainText: true
  OPML:
    mediaType: application/opml
    baseName: blogroll
    isPlainText: false
  search:
    mediaType: application/json
    baseName: index
    isPlainText: true
outputs:
  home:
    - HTML
    - RSS
    - llms
    - OPML
  page:
    - HTML
    - Markdown
# llms.txt END
