# yaml-language-server: $schema=schemas/hugo.json
baseURL: https://perrotta.dev
defaultContentLanguage: en
copyright: |
  ¬© 2021 - 2025 Thiago Perrotta ¬∑
    [some rights reserved](https://creativecommons.org/licenses/by-nc-sa/4.0/) ¬∑
    a fork of [hugo  ï‚Ä¢·¥•‚Ä¢ î bear](https://github.com/janraasch/hugo-bearblog/)
languageCode: en-us
enableRobotsTxt: true
markup:
  highlight:
    style: onedark
  goldmark:
    renderer:
      unsafe: true
rssLimit: 50
title: ¬¨ just serendipity üçÄ
menu:
  main:
    - name: ‚òÖ
      url: /tags/bestof/
      weight: 1
      params:
        emoji: ‚≠ê
    - name: Blog
      url: /posts/
      weight: 2
    - name: Coding
      url: /tags/coding/
      weight: 3
params:
  author:
    email: serendipity@perrotta.dev
    name: Thiago Perrotta
  description: not just serendipity, the blog from Thiago Perrotta
  appleTouchIcon: apple-touch-icon.png
  favicon: favicon.ico
permalinks:
  posts: "/:year/:month/:slug/"
disableKinds:
  - taxonomy

# llms.txt BEGIN
# layouts/_default/home.llms.txt
mediaTypes:
  text/llms:
    suffixes:
      - txt
outputFormats:
  llms:
    mediaType: text/llms
    baseName: llms
    isPlainText: true
outputs:
  home:
    - HTML
    - RSS
    - llms
# llms.txt END
