# yaml-language-server: $schema=https://json.schemastore.org/hugo.json
baseURL: https://perrotta.dev
defaultContentLanguage: en
copyright: |
  Â© 2021 - 2025 Thiago Perrotta Â·
    [some rights reserved](https://creativecommons.org/licenses/by-nc-sa/4.0/) Â·
    a fork of [hugo Ê•â€¢á´¥â€¢Ê” bear](https://github.com/janraasch/hugo-bearblog/)
languageCode: en-us
enableRobotsTxt: true
markup:
  highlight:
    style: onedark
  goldmark:
    renderer:
      unsafe: true
rssLimit: 50
title: Â¬ just serendipity ğŸ€
menu:
  main:
    - name: Home
      url: /
      weight: -1
    - name: Blog
      url: /posts/
      weight: 1
    - name: â˜…
      url: /tags/bestof/
      weight: 2
params:
  author:
    email: serendipity@perrotta.dev
    name: Thiago Perrotta
  description: not just serendipity, the blog from Thiago Perrotta
  appleTouchIcon: apple-touch-icon.png
  favicon: favicon.ico
permalinks:
  posts: "/:year/:month/:slug/"
disableKinds:
  - taxonomy
