name: Prek auto-update

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prek-auto-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install prek
        uses: j178/prek-action@bf23d25b07ca5c2f51e3b9f20ac80e09e1d4c20c # v1.6.5
        with:
          install-only: true

      - name: Run prek auto-update
        run: prek auto-update --freeze --jobs "$(nproc)"

      # hugo build
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
      - uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
        with:
          hugo-version: "0.140.0"

      - uses: j178/prek-action@bf23d25b07ca5c2f51e3b9f20ac80e09e1d4c20c # v1.6.5
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bot/prek-autoupdate
          delete-branch: true
          title: Auto-update prek hooks
          commit-message: Auto-update prek hooks
          body: |
            Update tool versions in prek configs to latest version.
          labels: |
            automated
            dependencies
